spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/my_db
    username: my_user
    password: my_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis-container
      port: 6379
    mongodb:
      uri: mongodb://mongodb-container:27017/my_db
      auto-index-creation: true
